### ISSUE TITLE
Stereotypes do not display when common.puml included

### ISSUE THREAD

**Issue by dannief** [tupadr3/plantuml-icon-font-sprites#21]
The following displays correctly with the stereotype
```
@startuml
rectangle "Front End" <<React>>
@enduml
```

![image](https://user-images.githubusercontent.com/6110488/107091257-7abc8b00-67cf-11eb-85da-d396a4dc3ef4.png)

However when common.puml is included, the stereotype no longer displays
```
@startuml
!include <tupadr3/common>
rectangle "Front End" <<React>>
@enduml
```

![image](https://user-images.githubusercontent.com/6110488/107091418-c4a57100-67cf-11eb-84f2-596c7ac0e42c.png)

Is there something I am missing?

Thanks

**Comment by Potherca** [comment]
The reason the stereotype is hidden is because the [`common.puml` has a call to `hide stereotype`](https://github.com/tupadr3/plantuml-icon-font-sprites/blob/HEAD/common.puml#L21).

In order to display stereotypes, use `show stereotype` after including `common.puml`:

```
@startuml
!include <tupadr3/common>
show stereotype
rectangle "Front End" <<React>>
@enduml
```

![](http://www.plantuml.com/plantuml/png/1S713G8X40NGErMCsu07huJiHGkm0m8_QW8pPFWJO_U-TsvMPyoHBXzj8peaCrRjVhisczEqfFsshsp2OVmj94TZrTU070ytfTor7vBp4xMnb7H2Uypn1m00)
